/* Generated By:JavaCC: Do not edit this line. CardGrammarConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CardGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPELL = 7;
  /** RegularExpression Id. */
  int PERMANENT = 8;
  /** RegularExpression Id. */
  int CREATURE = 9;
  /** RegularExpression Id. */
  int ELEMENT = 10;
  /** RegularExpression Id. */
  int COST = 11;
  /** RegularExpression Id. */
  int MONO = 12;
  /** RegularExpression Id. */
  int DUO = 13;
  /** RegularExpression Id. */
  int TRIO = 14;
  /** RegularExpression Id. */
  int SUBTYPE = 15;
  /** RegularExpression Id. */
  int STAT = 16;
  /** RegularExpression Id. */
  int TEXT = 17;
  /** RegularExpression Id. */
  int ELEMENTS = 18;
  /** RegularExpression Id. */
  int LBLOCK = 19;
  /** RegularExpression Id. */
  int RBLOCK = 20;
  /** RegularExpression Id. */
  int LPAR = 21;
  /** RegularExpression Id. */
  int RPAR = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int WORD = 24;
  /** RegularExpression Id. */
  int PUNCT = 25;
  /** RegularExpression Id. */
  int MATH = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int LETTER = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"SPELL\"",
    "\"PERMANENT\"",
    "\"CREATURE\"",
    "\"ELEMENT\"",
    "\"COST\"",
    "\"MONO\"",
    "\"DUO\"",
    "\"TRIO\"",
    "\"SUBTYPE\"",
    "\"STAT\"",
    "\"TEXT\"",
    "<ELEMENTS>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "<WORD>",
    "<PUNCT>",
    "<MATH>",
    "<DIGIT>",
    "<LETTER>",
  };

}
