/* Generated by JTB 1.4.7 */
package parser.syntaxtree;

import parser.visitor.*;

public class Permanent implements INode {

	public NodeToken f0;

	public Name f1;

	public NodeToken f2;

	public Element f3;

	public Cost f4;

	public Subtype f5;

	public Text f6;

	public NodeToken f7;

	private static final long serialVersionUID = 147L;

	public Permanent(final NodeToken n0, final Name n1, final NodeToken n2,
			final Element n3, final Cost n4, final Subtype n5, final Text n6,
			final NodeToken n7) {
		f0 = n0;
		f1 = n1;
		f2 = n2;
		f3 = n3;
		f4 = n4;
		f5 = n5;
		f6 = n6;
		f7 = n7;
	}

	@Override
	public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
		return vis.visit(this, argu);
	}

	@Override
	public <R> R accept(final IRetVisitor<R> vis) {
		return vis.visit(this);
	}

	@Override
	public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
		vis.visit(this, argu);
	}

	@Override
	public void accept(final IVoidVisitor vis) {
		vis.visit(this);
	}

}
