/* Generated by JTB 1.4.7 */
package parser.syntaxtree;

import parser.visitor.*;

public class Trio implements INode {

	public NodeToken f0;

	public NodeToken f1;

	public NodeToken f2;

	public NodeToken f3;

	public NodeToken f4;

	public NodeToken f5;

	public NodeToken f6;

	public NodeToken f7;

	public NodeToken f8;

	private static final long serialVersionUID = 147L;

	public Trio(final NodeToken n0, final NodeToken n1, final NodeToken n2,
			final NodeToken n3, final NodeToken n4, final NodeToken n5,
			final NodeToken n6, final NodeToken n7, final NodeToken n8) {
		f0 = n0;
		f1 = n1;
		f2 = n2;
		f3 = n3;
		f4 = n4;
		f5 = n5;
		f6 = n6;
		f7 = n7;
		f8 = n8;
	}

	@Override
	public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
		return vis.visit(this, argu);
	}

	@Override
	public <R> R accept(final IRetVisitor<R> vis) {
		return vis.visit(this);
	}

	@Override
	public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
		vis.visit(this, argu);
	}

	@Override
	public void accept(final IVoidVisitor vis) {
		vis.visit(this);
	}

}
